language: java
env:
  global:
  - GIT_USERNAME=Travis CI
  - GIT_EMAIL=builds@travis-ci.com
  - TAG=$(./pipeline.sh getProperty version gradle.properties)
  - RELEASE_FILE=build/libs/encryptor-$TAG.jar
  - RELEASE_POM=build/pom.xml
  - LAST_COMMIT_MESSAGE=$(git log -1 --pretty=%B | tr -d '\n')
  - CD_COMMIT_MESSAGE='[travis] Bump version number'
  - GITHUB_USER=dermotmburke
  - secure: JSUDyYXKteUYQvmah2dZd+pFTbL0v8imQfLp20qePA3CKf5YLKdqldCp2k2QiJLqa4FZUqnzqjUuzC/jDWexiiaZ6ZhH/AF8kFvsxJTNPbDQmDtly4/33CC+E41L1YqDOFYkyBlVN6jNe93GVeL5HHkqgzox2qnaL25lRAgdhJGXe/1ScbGL+4ylSmQFecLh4Ei7T0FEYWunUrL2f3iTrdit+5kZHkMNexZUHKtsP7uDulFcWsrpH2DLri4lwJOuEe7scW8DBWK/qC2BM+ewHiXEKylk2rezMNtVXhW3e90uWT7lSDsWWj41D803rnVEMAjoW7sLGqokatCwEtIWnr8bmH+SUYnnJ7HyOAe5mklLA9P/CqLkxIRRh4NMy4RC6D7NagiJs6QoROQl/0b+A7+WWfsAVc/K2y+QEtXYE7tSoK00grwXagKzXFEfAEnI8LNjCVXAOFsRWsDK+1WYBoo71ev9ZXQ9eyo1z7ymstaY1mXmR8UaASoo6Ml7SxZpnUHSpSKr1fIGqGfdS3rTzuw0aEDzR6AECfBP49wzdbJixqXMQni7nv8YeAgMFRrDFdJiNNWCsWztQjVILT+z7pyPSvG6rTRTKX4/tNC9669A7Jo5Da43Pi0MMTX56gZq0JOtLePonChhdbulaV6EMmViCvP15AaCxuZ7XSv+KDo=
script:
- ./pipeline.sh build
before_deploy:
- ./pipeline.sh tag
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
  secure: h0kv9rXt90x/A5Rz848tHvgJy5+GkRuSKcphpdn8ELRe3cZvl7zzmz9UsAUgjNpZXGGg0zI6nLfNkYSYWRDWU98IrQQrqsJBV1e2NRl11rNRlhAAC0jEbOhFyYOdgn9jyVdQ10j90/HF/aoXmyzSUk/RCWfP+02hR+5jSUV3lRzxvRcRoFERN1gaEbdRYD3ZpTut5j+kW/4wUZqgWG4gq6UDWXlu2xZKpKLWArfaUZy/V8vNrLvdHh6y5xxtpd1ycjB4SDlh9GoIKfQ1SGE+7sjZs7dPiYxRJK71Wj3ugnRuQkRJB87iEKJ5JOW7Io8pkxp9+j6/50mF7obU66VYPXnIFGv0qYh7LMBsZnQHJJR/b58yZqooQqRow7Mw6PYDnmBrshK+SwXzw28v2AYO4FWxQSGHLD1SQPROXSRuVJnVPATzdKhNGThVTRlvQoznzAng+ovTqGcVvqD7gjdRUL7Ko0uC//LbN2Nj2bJJ2l12ApVBZPq07tqpMo25+fE0NbWpBn4nSVcrZcqcX0a5VxV/VyknUZe6uyMcdagYrRDCKSwSxAnTtSQ5xtnNugfBOJTyR+3vrdBRgFHq0Je8F/IwWwB+m3EO3HnaIrLX2moYaSnJmwnGHQ1g2thq5loP6MQ0jmMCTMl8rwW0z6/KNfTwsxwp4TCxIWFHb6vDyg4=  file:
    - "${RELEASE_FILE}"
    - "${RELEASE_POM}"
  on:
    branch: master
    tags: false
    condition: '"${LAST_COMMIT_MESSAGE}" != "${CD_COMMIT_MESSAGE}"'
after_deploy:
- ./pipeline.sh bump